cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'ack'
brew 'coreutils'
brew 'go'
brew 'grc'
brew 'imagemagick'
brew 'libgit2'
brew 'openssl'
brew 'node'
brew 'readline'
brew 'postgresql'
brew 'ruby-build'
brew 'rbenv'
brew 'roundup'
brew 'wget'
brew 'ansible'
brew 'apache-spark'
brew 'docker'

cask '1password'
cask 'atom'
cask 'firefox'
cask 'google-chrome'
cask 'slack'
cask 'steam'
cask 'tunnelbear'
cask 'vlc'
cask 'virtualbox'
cask 'vagrant'
